version: 1.0

num_classes: 2

classes: ["background", "building"]

class_to_color:
  "background": 0
  "building": 255

imagesize: 512

train:
  imagefolder: "data/images/train"
  labelfolder: "data/masks/train"
  lidarfolder: "data/lidar/train"
  pointfolder: "data/point/train"
  batchsize: 8
  shuffle: True
val:
  imagefolder: "data/images/val"
  labelfolder: "data/images/val"
  lidarfolder: "data/lidar/val"
  pointfolder: "data/point/val"
  batchsize: 1
  shuffle: False
test:
  imagefolder: "data/images/test"
  lidarfolder: "data/lidar/test"
  pointfolder: "data/point/test"
  batchsize: 1
  shuffle: False