version: 1.0

num_classes: 2

classes: ["background", "building"]

class_to_color:
  "background": 0
  "building": 255

imagesize: 500

test:
  imagefolder: "../data/images/test"
  labelfolder: "../data/masks/test"
  batchsize: 1
  shuffle: False