version: 1.0

num_classes: 2

classes: ["background", "building"]

class_to_color:
  "background": 0
  "building": 255

imagesize: 512

train:
  imagefolder: "data/train"
  labelfolder: "data/train_labels"
  batchsize: 8
  shuffle: True
val:
  imagefolder: "data/val"
  labelfolder: "data/val_labels"
  batchsize: 1
  shuffle: False
test:
  imagefolder: "data/test"
  batchsize: 1
  shuffle: False