# This is a basic workflow to help you get started with Actions

name: Evaluation Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: "Checkout private repo with PAT"
        run: |
          git clone https://${{ secrets.PAT_EVALUATION_DATA }}@github.com/Sjyhne/mapai_evaluation_data.git data

      - name: "What is in my repo"
        run: ls
      
      - name: "Print build finished"
        run: echo "Build finished"
      
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          # File containing the Python version to use. Example: .python-version
          python-version-file: .python-version

      # Runs a set of commands using the runners shell
      - name: Evaluation
        run: |
          cd team_template
          pip3 install -r requirements.txt
          python3 evaluate_task_1.py --data_percentage 0.01
          echo Finished evaluation, exiting
